### ISSUE TITLE
정의가 존재하지 않는 버그

### ISSUE THREAD

**Issue by JP3Pe** [belf-kr/api-gateway#14]
![image](https://user-images.githubusercontent.com/45834750/119229027-e3e2c700-bb50-11eb-8ea7-0c65abce4d93.png)
오늘 작업하신 merge 충돌 관련 내용을 작업하다 해당 정의들이 파일에서 삭제된게 아닐까 싶습니다.
확인 부탁드립니다.

**Comment by Seungup** [comment]
확인해보겠습니다

**Comment by Seungup** [comment]
버그 수정 후 feature/migration 에 push 했습니다.
