### ISSUE TITLE
환경설정을 ConfigModule 사용해 todo 서비스와 맞추기

### ISSUE THREAD

**Issue by JP3Pe** [belf-kr/api-gateway#21]
서버의 listen port, 추 후 추가될 설정 옵션 등을 todo 서비스와 맞출 필요가 존재

**Comment by JP3Pe** [comment]
@parkgang API의 설정 관련 코드를 todo 코드와 동일하게 작성하려고 합니다.
현재 배포 시스템은 API gateway 코드를 사용할 때 .env 파일을 사용하나요?

**Comment by parkgang** [comment]
@JP3Pe 추가된 내용을 `README.md` 에 반영해주세요.

**Comment by parkgang** [comment]
@JP3Pe 이거 누락하신거 같아서 다시 open 합니다.

**Comment by JP3Pe** [comment]
@parkgang 새롭게 추가된 .env 환경 변수에 대한 설명을 업데이트 했습니다.

**Comment by parkgang** [comment]
@JP3Pe 문서가 잘못된 거 같습니다. Server Port Default 3000 이 기제되어 있지 않습니다.

**Comment by JP3Pe** [comment]
@parkgang README.md 파일내 SERVER_PORT 설명을 기입 해 두었는데 무엇을 말씀 하신건가요?

**Comment by parkgang** [comment]
> @parkgang README.md 파일내 SERVER_PORT 설명을 기입 해 두었는데 무엇을 말씀 하신건가요?

@JP3Pe Default 값이 기입되어 있지 않습니다.

**Comment by JP3Pe** [comment]
@parkgang 기폰 Port 값 추가했습니다.

**Comment by parkgang** [comment]
> @parkgang 기폰 Port 값 추가했습니다.

네, 확인했습니다. 이제 기능 개발에 집중 해 주세요.
