### ISSUE TITLE
서브모듈이 K8sServiceDNS 사용 시 API 하위의 서비스들 listen port가 전부 3000으로 작성된 문제

### ISSUE THREAD

**Issue by JP3Pe** [belf-kr/api-gateway#22]
localhost에서 K8sServiceDNS 함수 호출해서 API와 함께 돌아가는 서비스들의 listen port를 지정하는 로직이 존재.
해당 로직은 IP(DNS) 정보가 서로 다르고 port가 동일한 K8S의 포드 환경에서는 문제가 없지만, localhost로 URL이 전부 동일 한 경우 3000포트로 모든 서비스들의 listen port가 동일하게 설정되어 문제 발생요지 큼.

**Comment by parkgang** [comment]
@JP3Pe 해당 이슈가 각각의 service module에 맞는 환경변수를 생성하는 것이 맞나요?

**Comment by JP3Pe** [comment]
@parkgang API 서비스에서 다른 서비스들을 바인딩 해 줄 때 K8sServiceDNS 함수를 사용하고, 이 곳에 입력된 port 값을 API 게이트웨이 내 각 서비스들이 HttpModule.register를 사용해 baseURL로 바인딩 해 주는것으로 이해했습니다.

로컬 환경에서는 각 서비스들의 listen port 값이 prod 값이랑 동일한 3000이 아니니, API 게이트웨이 내 .env.dev 파일등을 생성해 그 내부에 TODO_SERVER_PORT 등을 입력 후 value를 todo 서비스의 레포내 .env.dev 값과 동일하게 맞추어 줄 생각입니다.

**Comment by JP3Pe** [comment]
@parkgang 각 서비스 모듈에 해당되는 포트 값을 저장하는 환경변수를 말씀하신거라면, 그것이 맞다고 할 수 있겠네요.
