### ISSUE TITLE
CORS 문제 해결 필요

### ISSUE THREAD

**Issue by algo2000** [belf-kr/api-gateway#26]
`Access to XMLHttpRequest at 'https://api-gateway.qa.belf.xyz/todo/today-todos' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`
API접근을 위한 CORS 처리가 필요합니다.

**Comment by JP3Pe** [comment]
@algo2000 
`Access-Control-Allow-Origin: *`
이 내용이 HTTP response header에 없으면 되는거죠?
