### ISSUE TITLE
npm 패키지 버전 업데이트

### ISSUE THREAD

**Issue by JP3Pe** [belf-kr/api-gateway#38]
npm 패키지들의 버전을 최신 버전으로 업데이트합니다.

**Comment by parkgang** [comment]
@JP3Pe 어떤 package 인가요?

**Comment by JP3Pe** [comment]
@parkgang 추가나 삭제는 없고 단순 설치된 패키지들의 버전을 npm update 등의 명령어로 업데이트 했습니다.

**Comment by parkgang** [comment]
@JP3Pe 음 지금 서버 죽어있는데 오늘 이것 이외에도 추가 코딩을 하실건가요?

**Comment by JP3Pe** [comment]
@parkgang 기존 코드를 리펙토링 하는 정도일 것이며, 추 후 서버 부팅이 필요한 경우 말씀드리겠습니다.

**Comment by parkgang** [comment]
@JP3Pe 사실 지금까지의 기능이 prod으로 올라가야하는 상황입니다. 된다면 리펙토링과 함께 prod애 올라갈 수 있도록 패치 노트 작업을 우선적으로 했으면 좋겠습니다.

**Comment by JP3Pe** [comment]
@parkgang 확인했습니다. 빠른 시일 내로 현 작업 내역을 리펙토링 해서 develop/main 브랜치에 적용 가능할 정도의 퀄리티로 우선적으로 변경하겠습니다.
