### ISSUE TITLE
API-GATEWAY END-POINT 추가하기

### ISSUE THREAD

**Issue by Seungup** [belf-kr/api-gateway#7]
uri: /
기능: jwt 토큰정보를 바탕으로 유저 정보 리턴 (임시)
조건: void

**Comment by Seungup** [comment]
uri: /status
기능: mock, api-gateway, prod 서버 상태 확인
조건: void

**Comment by JP3Pe** [comment]
develop 브랜치에 merge 된 커밋으로 판단돼 해당 이슈를 close 합니다.
@Seungup
